import { createClient, type SupabaseClient } from '@supabase/supabase-js'

/**
 * Community data layer.
 *
 * Reads go straight to Postgres with the publishable key, which is public by
 * design — row-level security is what protects the data, not the secrecy of
 * that key. Writes go through the same client but as a signed-in anonymous
 * user, because every write policy checks `auth.uid()`.
 *
 * "Signed in" here means Supabase anonymous auth: a real session with no email
 * and no password. Nobody types anything to get one, and the pseudonym attached
 * to it is generated by the database, never chosen.
 */

const url = import.meta.env.VITE_SUPABASE_URL as string | undefined
const anonKey = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.VITE_SUPABASE_ANON_KEY) as string | undefined

export const isConfigured = Boolean(url && anonKey)

let client: SupabaseClient | null = null
export function db(): SupabaseClient {
  if (!client) client = createClient(url!, anonKey!)
  return client
}

/* -------------------------------------------------------------------------- */
/*  Identity                                                                   */
/* -------------------------------------------------------------------------- */

export interface Profile {
  id: string
  display_name: string
}

let signingIn: Promise<Profile | null> | null = null

/**
 * Returns the current pseudonymous identity, creating one on first use.
 *
 * Deliberately lazy: reading the community needs no session at all, so nobody
 * is signed into anything merely for visiting. The session appears the first
 * time someone does something that needs to be attributable — joining, posting,
 * reacting.
 */
export async function ensureProfile(): Promise<Profile | null> {
  if (!isConfigured) return null
  if (signingIn) return signingIn

  signingIn = (async () => {
    const supabase = db()
    let { data: session } = await supabase.auth.getSession()
    if (!session.session) {
      const { error } = await supabase.auth.signInAnonymously()
      if (error) {
        signingIn = null
        throw new Error(
          error.message.includes('disabled')
            ? 'Community accounts are not switched on yet. Please try again later.'
            : error.message,
        )
      }
      ;({ data: session } = await supabase.auth.getSession())
    }
    const uid = session.session?.user.id
    if (!uid) return null

    // The trigger creates the profile; on a cold start it can lose the race.
    for (let attempt = 0; attempt < 5; attempt++) {
      const { data } = await supabase
        .from('profiles')
        .select('id, display_name')
        .eq('id', uid)
        .maybeSingle()
      if (data) return data as Profile
      await new Promise((r) => setTimeout(r, 300))
    }
    return null
  })()

  return signingIn
}

/** The identity if one already exists, without creating one. */
export async function currentProfile(): Promise<Profile | null> {
  if (!isConfigured) return null
  const { data } = await db().auth.getSession()
  const uid = data.session?.user.id
  if (!uid) return null
  const { data: profile } = await db()
    .from('profiles')
    .select('id, display_name')
    .eq('id', uid)
    .maybeSingle()
  return (profile as Profile) ?? null
}

/* -------------------------------------------------------------------------- */
/*  Community                                                                  */
/* -------------------------------------------------------------------------- */

export interface GlossaryEntry {
  term: string
  definition: string
}

export interface Community {
  id: string
  slug: string
  name: string
  tagline: string | null
  card_label: string | null
  intro_title: string | null
  intro_body: string | null
  topics: string[]
  glossary: GlossaryEntry[]
  guidelines: string | null
}

export async function fetchCommunity(slug = 'amr'): Promise<Community> {
  const { data, error } = await db()
    .from('communities')
    .select(
      'id, slug, name, tagline, card_label, intro_title, intro_body, topics, glossary, guidelines',
    )
    .eq('slug', slug)
    .single()
  if (error) throw new Error(error.message)
  return data as Community
}

export async function fetchTags(communityId: string): Promise<string[]> {
  const { data } = await db()
    .from('community_tags')
    .select('label')
    .eq('community_id', communityId)
    .order('sort_order')
  return (data ?? []).map((row) => row.label as string)
}

export async function fetchMemberCount(communityId: string): Promise<number> {
  const { count } = await db()
    .from('memberships')
    .select('profile_id', { count: 'exact', head: true })
    .eq('community_id', communityId)
  return count ?? 0
}

export async function isMember(communityId: string, profileId: string): Promise<boolean> {
  const { data } = await db()
    .from('memberships')
    .select('profile_id')
    .eq('community_id', communityId)
    .eq('profile_id', profileId)
    .maybeSingle()
  return Boolean(data)
}

export async function joinCommunity(communityId: string, profileId: string): Promise<void> {
  const { error } = await db()
    .from('memberships')
    .insert({ community_id: communityId, profile_id: profileId })
  if (error && error.code !== '23505') throw new Error(error.message)
}

export async function leaveCommunity(communityId: string, profileId: string): Promise<void> {
  await db()
    .from('memberships')
    .delete()
    .eq('community_id', communityId)
    .eq('profile_id', profileId)
}

/* -------------------------------------------------------------------------- */
/*  Stories                                                                    */
/* -------------------------------------------------------------------------- */

export const POST_TYPES = [
  { id: 'my_story', label: 'My Story' },
  { id: 'caregiver_story', label: 'Caregiver Story' },
  { id: 'question', label: 'Question' },
  { id: 'update', label: 'Update' },
] as const

export type PostType = (typeof POST_TYPES)[number]['id']

export const CONTENT_WARNINGS = [
  'Hospitalization',
  'Sepsis or critical illness',
  'Isolation',
  'Bereavement',
  'Medical trauma',
] as const

export const REACTIONS = [
  { id: 'support', label: 'Sending support' },
  { id: 'relate', label: 'I relate' },
  { id: 'helpful', label: 'Helpful' },
  { id: 'hopeful', label: 'Hopeful' },
] as const

export type ReactionKind = (typeof REACTIONS)[number]['id']

export interface Post {
  id: string
  community_id: string
  author_id: string
  post_type: PostType
  title: string | null
  body: string
  tags: string[]
  content_warning: string | null
  visibility: 'public' | 'members'
  allow_comments: boolean
  created_at: string
  author: string
  reactions: Record<ReactionKind, number>
  myReactions: ReactionKind[]
  commentCount: number
  bookmarked: boolean
  isMine: boolean
}

const POST_COLUMNS =
  'id, community_id, author_id, post_type, title, body, tags, content_warning, visibility, allow_comments, created_at'

function emptyCounts(): Record<ReactionKind, number> {
  return { support: 0, relate: 0, helpful: 0, hopeful: 0 }
}

/**
 * Loads stories plus the counts around them.
 *
 * Four small queries rather than one join: reaction and comment counts are
 * public, but which stories *you* reacted to or bookmarked is not, and keeping
 * those separate means the private half simply is not requested when nobody is
 * signed in.
 */
export async function fetchPosts(communityId: string, viewerId?: string | null): Promise<Post[]> {
  const supabase = db()
  const { data: rows, error } = await supabase
    .from('posts')
    .select(POST_COLUMNS)
    .eq('community_id', communityId)
    .order('created_at', { ascending: false })
    .limit(100)
  if (error) throw new Error(error.message)

  const posts = (rows ?? []) as Omit<
    Post,
    'author' | 'reactions' | 'myReactions' | 'commentCount' | 'bookmarked' | 'isMine'
  >[]
  if (posts.length === 0) return []

  const ids = posts.map((p) => p.id)
  const authorIds = [...new Set(posts.map((p) => p.author_id))]

  const [{ data: profiles }, { data: reactions }, { data: comments }, { data: bookmarks }] =
    await Promise.all([
      supabase.from('profiles').select('id, display_name').in('id', authorIds),
      supabase.from('reactions').select('post_id, profile_id, kind').in('post_id', ids),
      supabase.from('post_comments').select('post_id').in('post_id', ids),
      viewerId
        ? supabase.from('bookmarks').select('post_id').in('post_id', ids)
        : Promise.resolve({ data: [] as { post_id: string }[] }),
    ])

  const nameOf = new Map((profiles ?? []).map((p) => [p.id as string, p.display_name as string]))
  const bookmarked = new Set((bookmarks ?? []).map((b) => b.post_id as string))
  const commentCounts = new Map<string, number>()
  for (const c of comments ?? [])
    commentCounts.set(c.post_id as string, (commentCounts.get(c.post_id as string) ?? 0) + 1)

  const counts = new Map<string, Record<ReactionKind, number>>()
  const mine = new Map<string, ReactionKind[]>()
  for (const r of reactions ?? []) {
    const postId = r.post_id as string
    const kind = r.kind as ReactionKind
    if (!counts.has(postId)) counts.set(postId, emptyCounts())
    counts.get(postId)![kind] += 1
    if (viewerId && r.profile_id === viewerId) mine.set(postId, [...(mine.get(postId) ?? []), kind])
  }

  return posts.map((post) => ({
    ...post,
    author: nameOf.get(post.author_id) ?? 'Someone',
    reactions: counts.get(post.id) ?? emptyCounts(),
    myReactions: mine.get(post.id) ?? [],
    commentCount: commentCounts.get(post.id) ?? 0,
    bookmarked: bookmarked.has(post.id),
    isMine: Boolean(viewerId) && post.author_id === viewerId,
  }))
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

export async function fetchPost(id: string, viewerId?: string | null): Promise<Post | null> {
  // A hand-edited or stale URL is a 404, not a database error. Postgres rejects
  // a malformed uuid with a 400 that would otherwise surface as a broken page.
  if (!UUID.test(id)) return null
  const { data } = await db().from('posts').select(POST_COLUMNS).eq('id', id).maybeSingle()
  if (!data) return null
  const all = await fetchPosts(data.community_id as string, viewerId)
  return all.find((p) => p.id === id) ?? null
}

export interface NewPost {
  communityId: string
  postType: PostType
  title: string
  body: string
  tags: string[]
  contentWarning: string | null
  visibility: 'public' | 'members'
  allowComments: boolean
}

export async function createPost(input: NewPost, profileId: string): Promise<string> {
  const { data, error } = await db()
    .from('posts')
    // author_id is overwritten by the database trigger with auth.uid(); it is
    // sent only because the column is NOT NULL.
    .insert({
      community_id: input.communityId,
      author_id: profileId,
      post_type: input.postType,
      title: input.title.trim() || null,
      body: input.body.trim(),
      tags: input.tags,
      content_warning: input.contentWarning,
      visibility: input.visibility,
      allow_comments: input.allowComments,
    })
    .select('id')
    .single()
  if (error) throw new Error(error.message)
  return data.id as string
}

export async function deletePost(id: string): Promise<void> {
  const { error } = await db().from('posts').delete().eq('id', id)
  if (error) throw new Error(error.message)
}

export async function toggleReaction(
  postId: string,
  profileId: string,
  kind: ReactionKind,
  on: boolean,
): Promise<void> {
  const supabase = db()
  const { error } = on
    ? await supabase.from('reactions').insert({ post_id: postId, profile_id: profileId, kind })
    : await supabase
        .from('reactions')
        .delete()
        .eq('post_id', postId)
        .eq('profile_id', profileId)
        .eq('kind', kind)
  if (error && error.code !== '23505') throw new Error(error.message)
}

export async function toggleBookmark(
  postId: string,
  profileId: string,
  on: boolean,
): Promise<void> {
  const supabase = db()
  const { error } = on
    ? await supabase.from('bookmarks').insert({ post_id: postId, profile_id: profileId })
    : await supabase.from('bookmarks').delete().eq('post_id', postId).eq('profile_id', profileId)
  if (error && error.code !== '23505') throw new Error(error.message)
}

/* -------------------------------------------------------------------------- */
/*  Comments and reports                                                       */
/* -------------------------------------------------------------------------- */

export interface StoryComment {
  id: string
  post_id: string
  author_id: string
  body: string
  created_at: string
  author: string
  isMine: boolean
}

export async function fetchComments(
  postId: string,
  viewerId?: string | null,
): Promise<StoryComment[]> {
  const supabase = db()
  const { data } = await supabase
    .from('post_comments')
    .select('id, post_id, author_id, body, created_at')
    .eq('post_id', postId)
    .order('created_at')
  const rows = data ?? []
  if (rows.length === 0) return []

  const { data: profiles } = await supabase
    .from('profiles')
    .select('id, display_name')
    .in('id', [...new Set(rows.map((r) => r.author_id as string))])
  const nameOf = new Map((profiles ?? []).map((p) => [p.id as string, p.display_name as string]))

  return rows.map((row) => ({
    ...(row as Omit<StoryComment, 'author' | 'isMine'>),
    author: nameOf.get(row.author_id as string) ?? 'Someone',
    isMine: Boolean(viewerId) && row.author_id === viewerId,
  }))
}

export async function addComment(postId: string, body: string, profileId: string): Promise<void> {
  const { error } = await db()
    .from('post_comments')
    .insert({ post_id: postId, author_id: profileId, body: body.trim() })
  if (error) throw new Error(error.message)
}

export async function deleteComment(id: string): Promise<void> {
  const { error } = await db().from('post_comments').delete().eq('id', id)
  if (error) throw new Error(error.message)
}

export type ReportReason = 'identifying' | 'abusive' | 'distressing' | 'spam' | 'other'

export const REPORT_REASONS: { id: ReportReason; label: string }[] = [
  { id: 'identifying', label: 'It identifies someone' },
  { id: 'abusive', label: 'It is abusive' },
  { id: 'distressing', label: 'I am worried about the person who wrote it' },
  { id: 'spam', label: 'Spam' },
  { id: 'other', label: 'Something else' },
]

export async function report(
  target: { postId?: string; commentId?: string },
  reason: ReportReason,
  reporterId: string | null,
): Promise<void> {
  const { error } = await db()
    .from('reports')
    .insert({
      post_id: target.postId ?? null,
      comment_id: target.commentId ?? null,
      reporter_id: reporterId,
      reason,
    })
  // A duplicate means this person already reported it. Nothing to say.
  if (error && error.code !== '23505') throw new Error(error.message)
}

/** Initials for the avatar circles, from the generated pseudonym. */
export function initials(name: string): string {
  return name.slice(0, 2).toUpperCase()
}
